services:
  postgres:
    image: postgres:15
    container_name: residencia_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: residencia
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: residencia_redis
    ports:
      - "6379:6379"
